
name: Main Taski Workflow
on:
  push:
    branches:
      - main

jobs:
  chekout_and_print_tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        user: actions/checkout@v3

      - name: Print project tree
        run: tree .
